name: Gitleaks

on:
  push:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSfL \
            https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-x64.tar.gz \
            -o gitleaks.tar.gz

          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Verify Gitleaks
        run: |
          gitleaks version

      - name: Run Gitleaks
        run: |
          gitleaks git \
            --redact \
            --log-opts="--all" \
            .